name: NPM cache test on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Show Node.js version
        run: node --version

      - name: Show npm version
        run: npm --version

      - name: Display workspace info
        run: ls -la ${{ github.workspace }}

      - name: Install dependencies (clean installation based on package-lock.json)
        run: npm ci

      - name: List installed npm packages
        run: npm ls

      - name: Run test program
        run: npm start
