name: Test macOS runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest-large

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test curl commands
        run: |
          curl https://www.apple.com
          curl https://gdmf.apple.com
          curl https://init.push.apple.com
          curl https://courier.push.apple.com
